import type { Skill } from 'mu-harness';

// Skill bodies use single-quoted lines (backticks stay literal) and `~~~` code
// fences (so they do not collide with the model-facing ``` in the rendered prompt).
const lines = (...l: string[]): string => l.join('\n');

const INIT_AGENTS = lines(
  '`AGENTS.md` is the per-repo instruction file loaded into every session (it is read from the repo root and from any subdirectory the agent touches, most-specific last). Keep it as small as possible — include only what materially changes how an agent plans, executes, verifies, or delegates work in this repository.',
  '',
  '## When to use',
  '',
  '- The repo has no `AGENTS.md` and an agent keeps making avoidable mistakes here (wrong build/test command, editing generated files, skipping required verification).',
  '- You are onboarding this repository and want a minimal set of standing instructions.',
  '- An existing `AGENTS.md` has grown bloated or stale and needs trimming back to what still earns its place.',
  '',
  'Do NOT use it to document what is already discoverable from source, manifests, or a formatter — that belongs nowhere.',
  '',
  'The test for every line: *if this line were removed, would an agent be more likely to make a mistake?* If not, cut it.',
  '',
  '## Discovery (before writing)',
  '',
  'Read what already documents the repo: `README`, build manifests (`package.json` / `Cargo.toml` / `pyproject.toml` / `go.mod` / `deno.json` ...), CI config, any existing `AGENTS.md` or `CLAUDE.md`, other AI-tool instruction files, and relevant `docs/`.',
  'Detect: build / test / lint commands (especially non-standard ones), formatter config, monorepo layout, deployment workflow, and any existing agent-specific rules.',
  'Identify: non-obvious requirements, common failure modes, verification expectations, and delegation opportunities. Note what you could NOT infer from code alone — that is exactly what `AGENTS.md` is for.',
  '',
  '## Include only',
  '',
  '- Required workflows not obvious from the codebase',
  '- Non-standard build / test / lint / deploy commands',
  '- Repository-specific execution constraints',
  '- Verification required before completing work',
  '- Delegation rules (when to hand off to a sub-agent)',
  '- Architectural constraints agents frequently violate',
  '- Safety or operational restrictions',
  '- Required tools, environments, or where credentials live',
  '- Pointers to deeper docs by path, e.g. `@docs/architecture.md`',
  '',
  'Examples: "Run the project verify command (e.g. `make verify`) before marking work complete." / "Never edit files under `generated/`; regenerate them." / "Generate migrations with `scripts/new_migration.sh`."',
  '',
  '## Never include',
  '',
  'File trees, component inventories, generic coding advice, language conventions a formatter already enforces, long tutorials, API docs, onboarding material, or anything discoverable from manifests or source.',
  '',
  '## Structure',
  '',
  'Prefer focused sections, each holding only what earns its place:',
  '~~~markdown',
  '# AGENTS.md',
  '',
  '## Required Verification',
  'Commands an agent must run before completion.',
  '',
  '## Repository Constraints',
  'Rules agents are likely to violate.',
  '',
  '## Delegation',
  'When to use a specialized sub-agent or workflow.',
  '',
  '## References',
  '@docs/architecture.md',
  '@docs/deployment.md',
  '~~~',
  '',
  '## Large repos',
  '',
  'Place additional `AGENTS.md` files in subdirectories (`backend/AGENTS.md`, `frontend/AGENTS.md`, ...) holding only instructions specific to that area. Nested `AGENTS.md` is loaded automatically when the agent works there — do not duplicate root-level rules.',
  '',
  '## Pick the right mechanism',
  '',
  'Do not put a workflow into `AGENTS.md` if another primitive fits better:',
  '- **AGENTS.md** — behavior guidance the agent should always keep in mind.',
  '- **Skill** (`skills/<name>/SKILL.md`) — a reusable, on-demand workflow.',
  '- **Specialized sub-agent** — delegated expertise: security reviews, architecture analysis, performance investigations, release management, large refactors.',
  '',
  '## Write it',
  '',
  '`read` any existing `AGENTS.md` first and propose targeted edits rather than overwriting it. For a new file, `write` `AGENTS.md` at the repo root. Keep it minimal; finish by listing what you included and the one reason each line earns its place.',
);

const UPDATE_CONFIG = lines(
  'Modify mu coding-agent configuration. The config surface is small — there are no settings-file hooks, no env block, and no MCP-in-config; those do not exist here. Touch only what is listed below.',
  '',
  '## Where config lives',
  '',
  '| Surface | Path | Holds | Edit how |',
  '|---|---|---|---|',
  '| Global config | `~/.config/mu/config.json` | provider connection (`kind`, `baseUrl`, `apiKey`), `plugins`, `primaryAgents`, `capabilities`, `voiceModel` | edit JSON — read at startup, so relaunch to apply |',
  '| Runtime state | `~/.local/state/mu/state.json` | `model`, `theme`, `thinkingVisible` | prefer the in-app controls; the app owns this file |',
  '| Agent permissions | `~/.config/mu/agents/<name>.md` (global) or `<cwd>/.mu/agents/<name>.md` (project) | per-tool `allow` / `ask` / `deny` in the `tools` frontmatter | edit the agent file |',
  '',
  '(Paths follow `$XDG_CONFIG_HOME` / `$XDG_STATE_HOME` when those are set.)',
  '',
  '## CRITICAL: read before write, merge — do not replace',
  '',
  'Always `read` the target file first and merge changes in. For array fields (`plugins`, `primaryAgents`) and the `tools` map, ADD to what is already there — never overwrite the whole array or file.',
  '',
  '## Prefer the built-in path over hand-editing',
  '',
  '- **Model / theme / thinking visibility** — change these from inside the app (model selector, theme picker, thinking toggle). They live in `state.json`, which the app writes; hand-editing it is a last resort.',
  '- **Plugins** — use the CLI: `mu install <npm:spec | jsr:spec | ./path.ts>` and `mu uninstall <spec>`. Both merge the `plugins` array in `config.json` for you.',
  '- **Edit `config.json` directly** for: provider connection (`kind` / `baseUrl` / `apiKey`), `primaryAgents`, `capabilities`, and `voiceModel` (the speech-to-text model `/voice` sends recorded audio to on the same provider; when unset, `/voice` uses the selected chat model if it supports audio, otherwise reports unavailable — set it to an audio-capable model like `gemma-4-12b-qat`).',
  '- **Edit an agent file** to change what a tool may do without prompting (the permissions analog — there is no allow/deny array).',
  '',
  '## Clarify ambiguity first',
  '',
  'mu has no question tool — ask the user in plain text when the request is ambiguous: which surface to change (global config vs an agent file), whether to add to or replace an array, and which value when several are plausible. Do not guess.',
  '',
  '## Workflow',
  '',
  '1. Clarify intent if ambiguous.',
  '2. `read` the target file (`config.json`, the agent `.md`, or `state.json`).',
  '3. Merge carefully — preserve existing keys and array entries.',
  '4. `edit` the file (or `write` the full merged content if it does not exist yet).',
  '5. Confirm what changed. Note that `config.json` and agent files are read at startup, so a relaunch is needed to apply them.',
  '',
  '## Merging arrays (important)',
  '',
  'Adding a plugin — WRONG (drops existing plugins):',
  '~~~json',
  '{ "plugins": ["npm:my-plugin"] }',
  '~~~',
  'RIGHT (preserves existing, appends the new one):',
  '~~~json',
  '{',
  '  "kind": "llama-swap",',
  '  "baseUrl": "http://localhost:8080",',
  '  "plugins": ["npm:existing-plugin", "npm:my-plugin"]',
  '}',
  '~~~',
  '',
  '## Example tasks',
  '',
  '**Add a plugin** — prefer `mu install npm:some-plugin`. By hand: `read` `config.json`, append the spec to `plugins`, `edit`.',
  '',
  '**Let the build agent run a command without prompting** — this is a permission, so edit the agent, not `config.json`. Set a scoped grant in the agent `tools` map:',
  '~~~yaml',
  'tools:',
  '  bash:',
  '    "npm *": allow',
  '    "**": ask',
  '~~~',
  '',
  '**Point at a different provider** — `read` `config.json`, set `kind` / `baseUrl` / `apiKey`, `edit`, then tell the user to relaunch. Pick the actual model from the in-app selector.',
  '',
  '**Change which agents cycle** — set `primaryAgents` in `config.json`, e.g. `["build", "plan", "explorer"]` (defaults to `["build", "plan"]`).',
  '',
  '## Common mistakes',
  '',
  '- Replacing an array or whole file instead of merging.',
  '- Wrong surface: model/theme belong in `state.json` (set them in-app), permissions belong in the agent file, provider/plugins belong in `config.json`.',
  '- Invalid JSON — re-read after editing to confirm it still parses.',
  '- Editing without reading first.',
  '',
  '## Troubleshooting',
  '',
  '- A `config.json` change has no effect → it is read at startup; relaunch the agent.',
  '- A permission change is ignored → confirm you edited the agent that is actually active, that the `tools` glob matches (e.g. `"npm *"`), and that you relaunched.',
  '- A file is silently ignored → invalid JSON (`config.json` / `state.json`) or malformed frontmatter (agent `.md`). Re-read and fix the syntax.',
);

const FLOW = lines(
  'A disciplined loop for any non-trivial code change on a local model: **search → plan → implement → review**. Its purpose is to keep your own context small — push the heavy reading into sub-agents and pull back only their short briefs. Run the phases in order; skip one only when the change is genuinely trivial, and say so.',
  '',
  '## The rule that makes this work',
  '',
  'Do not read the repo into your own context. Each time you would open more than a couple of files to understand something, delegate it instead: call `subagent` with the `explorer` agent and a precise question, and keep only the brief it returns. Several independent questions go in ONE `subagent` call so they run in parallel. If you lack the `subagent` tool, switch to the build agent first (Tab) or do the minimum reading yourself.',
  '',
  '## 1. Search',
  '',
  'State the task in one sentence. Then delegate discovery: ask `explorer` for the exact `path:line` locations that the change touches, how they connect, and the gotchas. Do not plan until you have this map. One round is usually enough; ask a second, sharper question only if the first left a real gap.',
  '',
  '## 2. Plan',
  '',
  'From the brief alone, write a short plan: the files you will change, the order, and how you will verify. Keep it to the smallest diff that satisfies the task — list explicitly what you will NOT touch. If two designs are plausible, pick one and note why in a line; do not survey options.',
  '',
  '## 3. Implement',
  '',
  'Read a file immediately before editing it (briefs go stale). Make tight, local edits; prefer changing existing code over adding new files. Match the surrounding style — this repo is comment-free, so add no comments. Do one coherent slice at a time and keep the tree compiling.',
  '',
  '## 4. Review',
  '',
  'Before reporting done, verify. Run the project checks if feasible. Then delegate a fresh-eyes pass: `subagent` → `reviewer` with the diff range (e.g. `git diff` against where you started) and the concern "correctness + does it match the task". Fix what comes back that is real. For a larger change use the `review` skill instead. Report what you changed and the verification you ran — plainly, with real results.',
);

const DISCOVER = lines(
  'Build a fast mental map of an unfamiliar area WITHOUT loading it into your own context. Use when you need to understand how something works, where a feature lives, or how a change would ripple — before planning or editing.',
  '',
  '## Method',
  '',
  'Do not grep-and-read your way through the repo yourself; that burns the context a local model cannot spare. Instead delegate to the `explorer` sub-agent via `subagent`, and keep only the map it returns.',
  '',
  '- Frame 1–3 precise questions about the area (entry points, data flow, the seam a change would touch). Put independent questions in ONE `subagent` call so they run in parallel.',
  '- Each explorer brief should come back as: a one-sentence answer, the load-bearing `path:line` locations with a note each, how they connect, and the gotchas. That is all you keep.',
  '- Synthesize the briefs into a single short map for yourself or the user. Cite `path:line`; do not paste file bodies. Stop as soon as the question is answered — resist mapping the whole repo.',
  '',
  'If you do not have the `subagent` tool, switch to an agent that does (Tab to build) before starting, or read only the few entry-point files directly and stop.',
);

const DIAGNOSE = lines(
  'A discipline for hard bugs and regressions: **feedback loop → reproduce → hypothesise → instrument → fix → regression-test → clean up**. Use when something is broken, throwing, failing, or slow and the cause is not obvious. Skip a phase only with an explicit reason.',
  '',
  '## 1. Build a feedback loop — this is the skill',
  '',
  'Everything else is mechanical once you have a fast, deterministic pass/fail signal for the bug. Spend most of your effort here. In rough order, try: a failing test at the nearest seam; a curl/CLI invocation against a fixture diffed to a known-good output; replaying a captured payload through the code path in isolation; a throwaway harness that calls just the buggy path. For "sometimes wrong", loop the trigger many times to raise the reproduction rate until it is debuggable. A 2-second deterministic loop is worth far more than staring at code. If you genuinely cannot build one, stop and say so, listing what you tried.',
  '',
  '## 2. Reproduce',
  '',
  'Run the loop; confirm it produces the failure the user described (not a nearby one) and capture the exact symptom. Do not proceed until it reproduces.',
  '',
  '## 3. Hypothesise',
  '',
  'Write 3–5 ranked, falsifiable hypotheses before testing any — each stating a prediction ("if X is the cause, changing Y makes it disappear"). A hypothesis with no prediction is a vibe; sharpen or drop it. Use the `explorer` sub-agent to check code that would confirm or kill a hypothesis rather than reading widely yourself.',
  '',
  '## 4. Instrument',
  '',
  'Test one variable at a time. Prefer a debugger/REPL or targeted logs at the boundary that distinguishes two hypotheses — never "log everything and grep". Tag every temporary log with a unique prefix (e.g. `[DBG-a4f2]`) so cleanup is one grep. For performance, measure a baseline and bisect; do not guess.',
  '',
  '## 5. Fix + regression test',
  '',
  'If a correct seam exists, turn the minimised repro into a failing test, watch it fail, apply the fix, watch it pass, then re-run the original loop. If no honest seam exists, say so — that is itself a finding about the architecture.',
  '',
  '## 6. Clean up',
  '',
  'Remove every tagged log (grep the prefix), delete throwaway harnesses, confirm the original repro no longer reproduces, and state the confirmed cause in your report so the next person learns.',
);

const REVIEW = lines(
  'Review a set of changes along independent axes that must not contaminate each other, by running each axis as its own read-only sub-agent and aggregating the findings. Use to review a branch, a PR, or work-in-progress against a baseline.',
  '',
  '## 1. Pin the baseline and scope',
  '',
  'Establish what to compare against — a commit, branch, tag, or `main` (ask the user if unstated). Capture the diff range once with three dots so it is against the merge-base: `git diff <base>...HEAD`, and the commit list `git log <base>..HEAD --oneline`. Do NOT read the whole diff into your own context.',
  '',
  '## 2. Identify the sources each axis needs',
  '',
  '- **Correctness/spec** — what the change was supposed to do: the originating issue/PRD/task, or the task the user gave you.',
  '- **Standards** — how this repo writes code: `AGENTS.md`, `CLAUDE.md`, `CONTRIBUTING.md`, ADRs. Note formatter/type-checker config but do not re-check what tooling already enforces.',
  '',
  '## 3. Run the axes in parallel',
  '',
  'Send ONE `subagent` call with one `reviewer` task per axis so they run concurrently and in isolated context. Give each the diff range, the commit list, and its sources, with a tight brief:',
  '- *Correctness*: find real defects the diff introduces — wrong logic, broken edge cases, missing error handling, unmet requirements, scope creep. Each finding `path:line` + why it matters, worst first.',
  '- *Standards*: every place the diff violates a documented rule; cite the rule; separate hard violations from judgement calls; skip tooling-enforced points.',
  '',
  '## 4. Aggregate',
  '',
  'Present each axis under its own heading, lightly cleaned — do not merge or re-rank across axes, so one cannot mask the other. End with a one-line summary: count per axis and the single worst issue. Verify any finding before you present it as fact; drop the speculative ones.',
);

const REFACTOR = lines(
  'Change structure without changing behaviour, in safe incremental steps. Use to clean up, decouple, deepen shallow modules, or make code more testable — never to add features. The goal is concentration of complexity: a small interface in front of a deep implementation.',
  '',
  '## Find the opportunity',
  '',
  "Use the `explorer` sub-agent to locate the friction rather than reading widely yourself: where understanding one concept means bouncing between many small modules, where a module's interface is nearly as complex as its implementation (shallow), or where tightly-coupled code leaks across its seam. Apply the **deletion test** to anything you suspect is a needless pass-through: if deleting the module would make complexity vanish, it earns nothing; if complexity would reappear smeared across its callers, it is doing real work and should stay.",
  '',
  '## Establish a safety net first',
  '',
  'Refactoring without behaviour coverage is editing blind. Check (via `explorer`) whether the area has tests that exercise it through its public interface. If it does not and the change is non-trivial, add characterization tests for the current behaviour BEFORE touching structure — or tell the user the net is missing and let them decide.',
  '',
  '## Move in tiny steps',
  '',
  'Make each step as small as possible so the program works after every one (Fowler). One structural change per slice — rename, extract, inline, move — then re-run the tests/build before the next. Never mix a refactor with a behaviour change in the same slice; if you spot a bug, note it and fix it separately. Test behaviour through public interfaces, not internals, so the tests survive the refactor.',
  '',
  '## Finish',
  '',
  'Confirm behaviour is unchanged (tests/build green, and the public interface still does what it did). Report the structural change you made and why it concentrates complexity, in terms of what future changes and tests get easier.',
);

export const builtinSkills: Skill[] = [
  {
    name: 'flow',
    description:
      'Run a non-trivial change as search → plan → implement → review, delegating the heavy reading to explorer/reviewer sub-agents to keep context small. Use for any feature or fix that touches code you do not already fully understand.',
    prompt: FLOW,
  },
  {
    name: 'discover',
    description:
      'Map an unfamiliar area of the codebase via the explorer sub-agent and keep only the brief — fast orientation without loading files into context. Use before planning or editing code you do not know.',
    prompt: DISCOVER,
  },
  {
    name: 'diagnose',
    description:
      'Disciplined debugging: build a fast reproduction loop, then hypothesise → instrument → fix → regression-test → clean up. Use when something is broken, throwing, failing, or slow and the cause is not obvious.',
    prompt: DIAGNOSE,
  },
  {
    name: 'review',
    description:
      'Review a branch/PR/diff against a baseline along correctness and standards axes, each run as an isolated reviewer sub-agent and aggregated. Use to review changes before merging or when asked to review since a point.',
    prompt: REVIEW,
  },
  {
    name: 'refactor',
    description:
      'Restructure code without changing behaviour in tiny safe steps — deletion test to find shallow modules, a test net first, then incremental moves. Use for cleanup/decoupling/testability, never to add features.',
    prompt: REFACTOR,
  },
  {
    name: 'init',
    description:
      'Create or update AGENTS.md — the per-repo agent instructions loaded each session. Use when a repo has no AGENTS.md and agents keep tripping on its workflows, when onboarding the repo, or to trim a bloated one.',
    command: 'init',
    prompt: INIT_AGENTS,
  },
  {
    name: 'update-config',
    description:
      'View or change mu coding-agent configuration — provider/plugins/primaryAgents in config.json, model/theme via the app, and per-tool permissions in agent files. Use when asked to change a setting, add a plugin, switch provider, or adjust what an agent may do.',
    prompt: UPDATE_CONFIG,
  },
];
